-- =====================================================================================
-- Lead Funnel & Attribution Analytics : star schema (Oracle 23ai Free / 19c+)
-- Run as FUNNEL. Safe to re-run: the DROP block at the top clears previous objects.
-- Grain of each table is stated in its comment. Surrogate keys use identity columns.
-- =====================================================================================

-- ---- clean slate (ignore ORA-00942 on first run) -------------------------------------
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
            WHERE table_name IN ('FACT_SPEND','FACT_TOUCHPOINTS','FACT_LEADS',
                                 'DIM_CAMPAIGN','DIM_CHANNEL','DIM_COURSE','DIM_STAGE','DIM_DATE'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- ==================================== DIMENSIONS =====================================

-- Grain: one row per calendar day. Key is YYYYMMDD (readable, sortable).
CREATE TABLE dim_date (
  date_key          NUMBER(8)     NOT NULL,
  full_date         DATE          NOT NULL,
  day_name          VARCHAR2(3)   NOT NULL,
  is_weekend        NUMBER(1)     NOT NULL,
  week_start_date   DATE          NOT NULL,   -- Monday (ISO week)
  month_start_date  DATE          NOT NULL,
  month_num         NUMBER(2)     NOT NULL,
  quarter_num       NUMBER(1)     NOT NULL,
  year_num          NUMBER(4)     NOT NULL,
  CONSTRAINT pk_dim_date PRIMARY KEY (date_key),
  CONSTRAINT uq_dim_date_full UNIQUE (full_date),
  CONSTRAINT ck_dim_date_wknd CHECK (is_weekend IN (0,1))
);

-- Grain: one row per funnel stage (static lookup).
CREATE TABLE dim_stage (
  stage_key    NUMBER(1)     NOT NULL,
  stage_name   VARCHAR2(30)  NOT NULL,
  CONSTRAINT pk_dim_stage PRIMARY KEY (stage_key)
);

-- Grain: one row per marketing channel (built from config/channel_mapping.csv on Day 2).
CREATE TABLE dim_channel (
  channel_key    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  channel_name   VARCHAR2(50)  NOT NULL,
  channel_group  VARCHAR2(30)  NOT NULL,      -- Paid Search / Paid Social / Organic / Direct ...
  is_paid        NUMBER(1)     NOT NULL,
  CONSTRAINT pk_dim_channel PRIMARY KEY (channel_key),
  CONSTRAINT uq_dim_channel_name UNIQUE (channel_name),
  CONSTRAINT ck_dim_channel_paid CHECK (is_paid IN (0,1))
);

-- Grain: one row per campaign. '(none)' / unknown member is inserted by the ETL.
CREATE TABLE dim_campaign (
  campaign_key   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  campaign_id    VARCHAR2(40)  NOT NULL,
  campaign_name  VARCHAR2(120) NOT NULL,
  channel_key    NUMBER        NOT NULL,
  objective      VARCHAR2(30),
  start_date     DATE,
  end_date       DATE,
  CONSTRAINT pk_dim_campaign PRIMARY KEY (campaign_key),
  CONSTRAINT uq_dim_campaign_id UNIQUE (campaign_id),
  CONSTRAINT fk_campaign_channel FOREIGN KEY (channel_key) REFERENCES dim_channel (channel_key)
);

-- Grain: one row per course specialization. Kaggle's placeholder 'Select' becomes 'Unspecified' (Day 2).
CREATE TABLE dim_course (
  course_key       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  specialization   VARCHAR2(80)  NOT NULL,
  CONSTRAINT pk_dim_course PRIMARY KEY (course_key),
  CONSTRAINT uq_dim_course_spec UNIQUE (specialization)
);

-- ====================================== FACTS ========================================

-- Grain: one row per lead (Prospect ID).
-- source_channel_key / campaign_key describe the LEAD-CREATING touch (= last touch).
CREATE TABLE fact_leads (
  lead_key              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  prospect_id           VARCHAR2(60)  NOT NULL,
  lead_number           NUMBER,
  created_date_key      NUMBER(8)     NOT NULL,
  source_channel_key    NUMBER        NOT NULL,
  campaign_key          NUMBER,
  course_key            NUMBER,
  lead_origin           VARCHAR2(50),
  current_occupation    VARCHAR2(60),
  city                  VARCHAR2(60),
  total_visits          NUMBER,
  time_on_site_sec      NUMBER,
  page_views_per_visit  NUMBER(8,2),
  last_activity         VARCHAR2(80),
  max_stage_key         NUMBER(1)     NOT NULL,
  converted_flag        NUMBER(1)     NOT NULL,
  enrollment_date_key   NUMBER(8),
  commission_inr        NUMBER(10,2),
  CONSTRAINT pk_fact_leads PRIMARY KEY (lead_key),
  CONSTRAINT uq_fact_leads_prospect UNIQUE (prospect_id),
  CONSTRAINT fk_leads_created  FOREIGN KEY (created_date_key)    REFERENCES dim_date (date_key),
  CONSTRAINT fk_leads_enrolled FOREIGN KEY (enrollment_date_key) REFERENCES dim_date (date_key),
  CONSTRAINT fk_leads_channel  FOREIGN KEY (source_channel_key)  REFERENCES dim_channel (channel_key),
  CONSTRAINT fk_leads_campaign FOREIGN KEY (campaign_key)        REFERENCES dim_campaign (campaign_key),
  CONSTRAINT fk_leads_course   FOREIGN KEY (course_key)          REFERENCES dim_course (course_key),
  CONSTRAINT fk_leads_stage    FOREIGN KEY (max_stage_key)       REFERENCES dim_stage (stage_key),
  CONSTRAINT ck_leads_converted CHECK (converted_flag IN (0,1)),
  -- business rule: enrolled <=> has an enrollment date, reached stage 5 and earned commission
  CONSTRAINT ck_leads_enrol_rule CHECK (
    (converted_flag = 1 AND enrollment_date_key IS NOT NULL AND max_stage_key = 5 AND commission_inr IS NOT NULL)
    OR (converted_flag = 0 AND enrollment_date_key IS NULL AND max_stage_key < 5 AND commission_inr IS NULL))
);

-- Grain: one row per touchpoint in a lead's journey. touch_seq 1 = first touch.
CREATE TABLE fact_touchpoints (
  touchpoint_key  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  lead_key        NUMBER      NOT NULL,
  touch_seq       NUMBER(2)   NOT NULL,
  touch_date_key  NUMBER(8)   NOT NULL,
  channel_key     NUMBER      NOT NULL,
  campaign_key    NUMBER,
  CONSTRAINT pk_fact_touchpoints PRIMARY KEY (touchpoint_key),
  CONSTRAINT uq_touch_lead_seq UNIQUE (lead_key, touch_seq),
  CONSTRAINT fk_touch_lead     FOREIGN KEY (lead_key)       REFERENCES fact_leads (lead_key),
  CONSTRAINT fk_touch_date     FOREIGN KEY (touch_date_key) REFERENCES dim_date (date_key),
  CONSTRAINT fk_touch_channel  FOREIGN KEY (channel_key)    REFERENCES dim_channel (channel_key),
  CONSTRAINT fk_touch_campaign FOREIGN KEY (campaign_key)   REFERENCES dim_campaign (campaign_key)
);

-- Grain: one row per campaign per day (ad-platform export).
CREATE TABLE fact_spend (
  date_key      NUMBER(8)     NOT NULL,
  campaign_key  NUMBER        NOT NULL,
  impressions   NUMBER(12)    NOT NULL,
  clicks        NUMBER(12)    NOT NULL,
  spend_inr     NUMBER(12,2)  NOT NULL,
  CONSTRAINT pk_fact_spend PRIMARY KEY (date_key, campaign_key),
  CONSTRAINT fk_spend_date     FOREIGN KEY (date_key)     REFERENCES dim_date (date_key),
  CONSTRAINT fk_spend_campaign FOREIGN KEY (campaign_key) REFERENCES dim_campaign (campaign_key),
  CONSTRAINT ck_spend_nonneg CHECK (impressions >= 0 AND clicks >= 0 AND spend_inr >= 0),
  CONSTRAINT ck_spend_clicks CHECK (clicks <= impressions)
);

-- Indexes on join / filter columns used by the KPI views
CREATE INDEX ix_leads_created  ON fact_leads (created_date_key);
CREATE INDEX ix_leads_channel  ON fact_leads (source_channel_key);
CREATE INDEX ix_leads_campaign ON fact_leads (campaign_key);
CREATE INDEX ix_touch_channel  ON fact_touchpoints (channel_key);
CREATE INDEX ix_touch_campaign ON fact_touchpoints (campaign_key);

-- ================================ SEED STATIC DIMENSIONS =============================
INSERT ALL
  INTO dim_stage (stage_key, stage_name) VALUES (1, 'Lead Captured')
  INTO dim_stage (stage_key, stage_name) VALUES (2, 'Contacted')
  INTO dim_stage (stage_key, stage_name) VALUES (3, 'Qualified')
  INTO dim_stage (stage_key, stage_name) VALUES (4, 'Applied')
  INTO dim_stage (stage_key, stage_name) VALUES (5, 'Enrolled')
SELECT 1 FROM dual;

-- Calendar for 2026 (covers the 180-day lead window plus up-to-60-day enrollment lag)
INSERT INTO dim_date (date_key, full_date, day_name, is_weekend, week_start_date,
                      month_start_date, month_num, quarter_num, year_num)
SELECT TO_NUMBER(TO_CHAR(d, 'YYYYMMDD')),
       d,
       TO_CHAR(d, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH'),
       CASE WHEN d - TRUNC(d, 'IW') >= 5 THEN 1 ELSE 0 END,
       TRUNC(d, 'IW'),
       TRUNC(d, 'MM'),
       EXTRACT(MONTH FROM d),
       TO_NUMBER(TO_CHAR(d, 'Q')),
       EXTRACT(YEAR FROM d)
FROM (SELECT DATE '2026-01-01' + LEVEL - 1 AS d FROM dual CONNECT BY LEVEL <= 365);

COMMIT;

-- Smoke test: expect 365 dates and 5 stages
SELECT (SELECT COUNT(*) FROM dim_date)  AS date_rows,
       (SELECT COUNT(*) FROM dim_stage) AS stage_rows
FROM dual;
